# Site settings
title: "Loris Marini Resume"
description: "Resume using Jekyll and GitHub Pages sites."

plugins:
  - jekyll-seo-tag
  - jekyll-analytics

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Loris Marini"
resume_title:                   "Data Engineer and Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lorenzo.marini.au@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "0468 561 278"
resume_contact_address:         "U23 / 767 Botany Road"

resume_header_contact_info:     "U23 / 767 Botany Road • 0468 561 278 • lorenzo.marini.au@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: >
  <p>I am an Information Engineer with research experience in experimental Physics. I enjoy learning, building stuff and sharing knowledge. I like communicating complex ideas in a simple a reletable way, and I like speaking in public. I am passionate about communication and cognitive psicology, and I think empathy and trust are the foundations of good leadership. I like simple solutions to complex problems, I give my best in cross-functional teams, and I want to use technology to improve people's lives.
  </p>


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_recognition:     true
resume_section_experience:      true
resume_section_education:       true
resume_section_interests:       true
resume_section_projects:        true

resume_section_skills:          false
resume_section_associations:    false
resume_section_links:           false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/LorisMarini/"
  resume_twitter_url:           "https://twitter.com/home"
  resume_linkedin_url:          "https://www.linkedin.com/in/lorismarini/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Configure Google Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-146412145-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking


# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
