# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Loris Marini"
resume_title:                   "Engineer and Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lorenzo.marini.au@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "0468 561 278"
resume_contact_address:         "U23 / 767 Botany Road"

resume_header_contact_info:     "U23 / 767 Botany Road • 0468 561 278 • lorenzo.marini.au@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: >
  <p>I am critical thinker and team-player, with distinguished people skills and diverse technical background.
  I enjoy sharing knowledge and presenting in public, and I like simple solutions to complex problems.
  In my last experience, I worked at the intersection of data analysis, software development, and data engineering
  to develop a data-driven culture in a vibrant startup. I work best in small teams with complementary skills,
  where ideas flow fast and the technology developed improves people’s lives.</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_recognition:     true
resume_section_experience:      true
resume_section_education:       true
resume_section_interests:       true
resume_section_projects:        true

resume_section_skills:          false
resume_section_associations:    false
resume_section_links:           false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/LorisMarini/"
  resume_twitter_url:           "https://twitter.com/home"
  resume_linkedin_url:          "https://www.linkedin.com/in/lorismarini/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
